dbconnection:
   data_connection: "postgres://postgres:Postik123@localhost:5432/AircraftDemo"
   gorm_connection: "host=localhost port=5432 user=postgres password=Postik123 dbname=AircraftDemo sslmode=disable"
server:
  addr: ":9081"